[target.aarch64-apple-ios]
ar = "/home/ae/theos/toolchain/linux/iphone/bin/ar"
linker = "/home/ae/theos/toolchain/linux/iphone/bin/ld"

[build]
# rustflags = ["-Clink-arg=-fuse-ld=mold", "-Zthreads=8", "-Ctarget-cpu=native"]
# rustflags = ["-Clink-arg=-fuse-ld=mold", "-Zthreads=8"]
# rustflags = ["-Clink-arg=-fuse-ld=mold"]
# rustflags = ["-Zthreads=8"]
