theme="tfleet_dark"
# theme="fleet_dark"

[editor]
shell = ["fish", "-c"]
line-number = "relative"
idle-timeout = 0
rulers = [80, 100, 120]
cursorline = true

[editor.lsp]
# auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
