[eww.files]
eww = { target = "~/.config/eww", type = "symbolic" }

[funs.files]
"funs/a.fish" = { target = "~/.config/fish/functions/a.fish", type = "symbolic" }
"funs/toggle_gamemode.fish" = { target = "~/.config/fish/functions/toggle_gamemode.fish", type = "symbolic" }
"funs/connect.fish" = { target = "~/.config/fish/functions/connect.fish", type = "symbolic" }
"funs/init_br.fish" = { target = "~/.config/fish/functions/init_br.fish", type = "symbolic" }
"funs/sinit_br.fish" = { target = "~/.config/fish/functions/sinit_br.fish", type = "symbolic" }
"funs/fpath.fish" = { target = "~/.config/fish/functions/fpath.fish", type = "symbolic" }

[hypr.files]
hypr = { target = "~/.config/hypr", type = "symbolic" }

[helix.files]
"helix/config.toml" = { target = "~/.config/helix/config.toml", type = "symbolic" }
"helix/languages.toml" = { target = "~/.config/helix/languages.toml", type = "symbolic" }

[wofi.files]
wofi = { target = "~/.config/wofi", type = "symbolic" }
