[kanata.files]
kanata = { target = "~/.config/kanata", type = "symbolic" }

[eww.files]
eww = { target = "~/.config/eww", type = "symbolic" }

[sioyek.files]
sioyek = { target = "~/.config/sioyek", type = "symbolic" }

[cargo.files]
"cargo/config.toml" = { target = "~/.cargo/config.toml", type = "symbolic" }

[entries.files]
"entries/spotify-adblock.desktop" = { target = "~/.local/share/applications/spotify-adblock.desktop", type = "symbolic" }

[funs.files]
"funs/b.fish" = { target = "~/.config/fish/functions/b.fish", type = "symbolic" }
"funs/t.fish" = { target = "~/.config/fish/functions/t.fish", type = "symbolic" }
"funs/toggle_gamemode.fish" = { target = "~/.config/fish/functions/toggle_gamemode.fish", type = "symbolic" }
"funs/connect.fish" = { target = "~/.config/fish/functions/connect.fish", type = "symbolic" }
"funs/init_br.fish" = { target = "~/.config/fish/functions/init_br.fish", type = "symbolic" }
"funs/sinit_br.fish" = { target = "~/.config/fish/functions/sinit_br.fish", type = "symbolic" }
"funs/fpath.fish" = { target = "~/.config/fish/functions/fpath.fish", type = "symbolic" }

[hypr.files]
hypr = { target = "~/.config/hypr", type = "symbolic" }

[helix.files]
"helix/config.toml" = { target = "~/.config/helix/config.toml", type = "symbolic" }
"helix/languages.toml" = { target = "~/.config/helix/languages.toml", type = "symbolic" }

[wofi.files]
wofi = { target = "~/.config/wofi", type = "symbolic" }
